// Code generated by mockery v2.52.3. DO NOT EDIT.

package seller

import (
	models "github.com/arieleon_meli/proyecto-final-grupo-6/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// SellerRepository is an autogenerated mock type for the SellerRepository type
type SellerRepositoryMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *SellerRepositoryMock) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *SellerRepositoryMock) GetAll() (map[int]models.Seller, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[int]models.Seller
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[int]models.Seller, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[int]models.Seller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]models.Seller)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *SellerRepositoryMock) GetByID(id int) (models.Seller, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Seller
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (models.Seller, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) models.Seller); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Seller)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *SellerRepositoryMock) Save(_a0 *models.Seller) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Seller) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchByCID provides a mock function with given fields: _a0
func (_m *SellerRepositoryMock) SearchByCID(_a0 int) (models.Seller, bool) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SearchByCID")
	}

	var r0 models.Seller
	var r1 bool
	if rf, ok := ret.Get(0).(func(int) (models.Seller, bool)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) models.Seller); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Seller)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *SellerRepositoryMock) Update(_a0 models.Seller) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Seller) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSellerRepository creates a new instance of SellerRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSellerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SellerRepositoryMock {
	mock := &SellerRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
