// Code generated by mockery v2.52.3. DO NOT EDIT.

package product_record

import (
	models "github.com/arieleon_meli/proyecto-final-grupo-6/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ProductRecordServiceMock is an autogenerated mock type for the ProductRecordServiceMock type
type ProductRecordServiceMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ProductRecordServiceMock) Create(_a0 models.ProductRecordDocRequest) (*models.ProductRecordDocResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.ProductRecordDocResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ProductRecordDocRequest) (*models.ProductRecordDocResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(models.ProductRecordDocRequest) *models.ProductRecordDocResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductRecordDocResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(models.ProductRecordDocRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductRecordService creates a new instance of ProductRecordServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRecordServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRecordServiceMock {
	mock := &ProductRecordServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
