// Code generated by mockery v2.52.3. DO NOT EDIT.

package inbound_order

import (
	models "github.com/arieleon_meli/proyecto-final-grupo-6/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// InboundOrderServiceMock is an autogenerated mock type for the InboundOrderServiceMock type
type InboundOrderServiceMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: request
func (_m *InboundOrderServiceMock) Create(request models.RequestInboundOrder) (*models.InboundOrder, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.InboundOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(models.RequestInboundOrder) (*models.InboundOrder, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(models.RequestInboundOrder) *models.InboundOrder); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InboundOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(models.RequestInboundOrder) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInboundOrderServiceMock creates a new instance of InboundOrderServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInboundOrderServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InboundOrderServiceMock {
	mock := &InboundOrderServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
