// Code generated by mockery v2.52.3. DO NOT EDIT.

package product_record

import (
	models "github.com/arieleon_meli/proyecto-final-grupo-6/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ProductRecordRepositoryMock is an autogenerated mock type for the ProductRecordRepositoryMock type
type ProductRecordRepositoryMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ProductRecordRepositoryMock) Create(_a0 *models.ProductRecordDocResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ProductRecordDocResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductRecordRepository creates a new instance of ProductRecordRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRecordRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRecordRepositoryMock {
	mock := &ProductRecordRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
